export const documentViweColumns = [
  {
    colName: 'Employee Name',
    colWidth: 200,
    flexGrow: 3,
    col: 'EmployeeName',
    fixed: true,
    sortable: true,
    type: 'employeeName',
    field: 'EmployeeName',
    placeholder: 'Enter a Name',
    andOr: 'or',
    changeAndOr: false,
  },
  {
    colName: 'Job ID',
    colWidth: 200,
    flexGrow: 3,
    col: '_id',
    fixed: true,
    sortable: true,
    type: 'jobId',
    field: '_id',
    andOr: 'and',
    changeAndOr: false,
  },
  {
    colName: 'Job Code',
    colWidth: 200,
    flexGrow: 3,
    col: 'title',
    fixed: true,
    sortable: true,
    type: 'jobCode',
    field: 'code',
    placeholder: 'Enter a job code',
    andOr: 'and',
    changeAndOr: false,
  },
  {
    colName: 'Assigned By',
    colWidth: 200,
    flexGrow: 3,
    col: 'AssignedBy',
    fixed: true,
    sortable: true,
    type: 'assignedById',
    field: 'AssignedBy',
    placeholder: 'Enter a Name',
    andOr: 'or',
    changeAndOr: false,
  },
  {
    colName: 'Company',
    colWidth: 200,
    flexGrow: 3,
    col: 'Company',
    fixed: true,
    sortable: true,
    type: 'companyId',
    field: 'Company',
    andOr: 'or',
    changeAndOr: false,
  },
  {
    colName: 'Starting On',
    colWidth: 200,
    flexGrow: 3,
    col: 'StartingOn',
    fixed: true,
    sortable: true,
    type: 'startingOn',
    field: 'StartingOn',
    andOr: 'or',
    changeAndOr: false,
  },
  {
    colName: 'Package Assigned On',
    colWidth: 200,
    flexGrow: 3,
    col: 'PackageAssignedOn',
    fixed: true,
    sortable: true,
    type: 'packageAssignedOn',
    field: 'PackageAssignedOn',
    andOr: 'or',
    changeAndOr: false,
  },
  {
    colName: 'Starts by User',
    colWidth: 200,
    flexGrow: 3,
    col: 'StartsByUser',
    fixed: true,
    sortable: true,
    type: 'startByUserId',
    field: 'StartsByUser',
    andOr: 'or',
    changeAndOr: false,
  },
  {
    colName: 'Package Status',
    colWidth: 200,
    flexGrow: 3,
    col: 'PackageStatus',
    fixed: true,
    sortable: true,
    type: 'packageStatus',
    field: 'PackageStatus',
    andOr: 'or',
    changeAndOr: false,
  },
  {
    colName: 'Document Status',
    colWidth: 200,
    flexGrow: 3,
    col: 'DocumentStatus',
    fixed: true,
    sortable: true,
    type: 'documentStatus',
    field: 'DocumentStatus',
    andOr: 'or',
    changeAndOr: false,
  },
  {
    colName: 'Document Type',
    colWidth: 200,
    flexGrow: 3,
    col: 'DocumentType',
    fixed: true,
    sortable: true,
    type: 'documentType',
    field: 'DocumentType',
    andOr: 'or',
    changeAndOr: false,
  },
  {
    colName: 'Package Name',
    colWidth: 200,
    flexGrow: 3,
    col: 'PackageName',
    fixed: true,
    sortable: true,
    type: 'packageName',
    field: 'PackageName',
    andOr: 'or',
    changeAndOr: false,
  },
  {
    colName: 'Department',
    colWidth: 200,
    flexGrow: 3,
    col: 'Department',
    fixed: true,
    sortable: true,
    type: 'department',
    field: 'Department',
    andOr: 'and',
    changeAndOr: false,
  },
  {
    colName: 'Document Name',
    colWidth: 200,
    flexGrow: 3,
    col: 'DocumentName',
    fixed: true,
    sortable: true,
    type: 'documentName',
    field: 'DocumentName',
    andOr: 'and',
    changeAndOr: false,
  },
  {
    colName: 'Job Title',
    colWidth: 200,
    flexGrow: 3,
    col: 'JobTitle',
    fixed: true,
    sortable: true,
    type: 'jobTitle',
    field: 'JobTitle',
    placeholder: 'Enter a job title',
    andOr: 'and',
    changeAndOr: false,
  },
];

export const DocumentViewData = [
  {
    employeeName: '李一',
    documentType: 'Offer Letter',
    documentName: 'Huawei-Confidential',
    approveStatus: 'PENDING',
    PackageAssignedOn: '2022-02-23T01:16:52Z',
    packageName: 'APAC W2 Hire',
    completionStatus: 'COMPLETE',
    StartingOn: '2022-02-23T01:16:52Z',
    jobTitle: 'String',
    company: 'String',
    jobId: 1,
    jobCode: 'String',
    department: 'String',
    startedBy: 'String',
    createdBy: 'String',
    docStatus: 'Missing',
    packageStatus: 'Incomplete',
  },
  {
    employeeName: '王二',
    documentType: 'Offer Letter',
    documentName: 'Huawei-Confidential',
    approveStatus: 'PENDING',
    PackageAssignedOn: '2022-02-23T01:16:52Z',
    packageName: 'APAC W2 Hire',
    completionStatus: 'COMPLETE',
    StartingOn: '2022-02-23T01:16:52Z',
    jobTitle: 'String',
    company: 'String',
    jobId: 1,
    jobCode: 'String',
    department: 'String',
    startedBy: 'String',
    createdBy: 'String',
    docStatus: 'Missing',
    packageStatus: 'Incomplete',
  },
];

export const documentTypeData = [
  {
    value: 'BACKGROUND_CHECK',
    label: 'Background Check',
  },
  {
    value: 'DRUG_TEST',
    label: 'Drug Test',
  },
  {
    value: 'EMPLOYMENT_AGREEMENT',
    label: 'Employment Agreement',
  },
  {
    value: 'I_9_MATERIALS',
    label: 'I-9 Materials',
  },
  {
    value: 'OFFER_LETTER',
    label: 'Offer Letter',
  },
  {
    value: 'PERSONAL_INFORMATION_FORM',
    label: 'Personal Information Form',
  },
  {
    value: 'TAX_FORM',
    label: 'Tax Form',
  },
];
export const documentStatusData = [
  {
    value: 'ACCEPTED',
    label: 'Accepted',
  },
  {
    value: 'MISSING',
    label: 'Missing',
  },
  {
    value: 'REJECTED',
    label: 'Rejected',
  },
  {
    value: 'PENDING',
    label: 'Pending',
  },
];
export const PackageStatusData = [
  {
    value: 'COMPLETE',
    label: 'Complete',
  },
  {
    value: 'INCOMPLETE',
    label: 'Incomplete',
  },
];
export const packagetViweColumns = [
  {
    colName: 'Employee Name',
    colWidth: 200,
    flexGrow: 3,
    col: 'EmployeeName',
    fixed: true,
    sortable: true,
    type: 'employeeName',
    field: 'EmployeeName',
    placeholder: 'Enter a Name',
    andOr: 'or',
    changeAndOr: false,
  },
  {
    colName: 'Job ID',
    colWidth: 200,
    flexGrow: 3,
    col: '_id',
    fixed: true,
    sortable: true,
    type: 'jobId',
    field: '_id',
    andOr: 'and',
    changeAndOr: false,
  },
  {
    colName: 'Assigned By',
    colWidth: 200,
    flexGrow: 3,
    col: 'AssignedBy',
    fixed: true,
    sortable: true,
    type: 'assignedById',
    field: 'AssignedBy',
    placeholder: 'Enter a Name',
    andOr: 'or',
    changeAndOr: false,
  },
  {
    colName: 'Company',
    colWidth: 200,
    flexGrow: 3,
    col: 'Company',
    fixed: true,
    sortable: true,
    type: 'companyId',
    field: 'Company',
    andOr: 'or',
    changeAndOr: false,
  },
  {
    colName: 'Starting On',
    colWidth: 200,
    flexGrow: 3,
    col: 'StartingOn',
    fixed: true,
    sortable: true,
    type: 'startingOn',
    field: 'StartingOn',
    andOr: 'or',
    changeAndOr: false,
  },
  {
    colName: 'Package Assigned On',
    colWidth: 200,
    flexGrow: 3,
    col: 'PackageAssignedOn',
    fixed: true,
    sortable: true,
    type: 'packageAssignedOn',
    field: 'PackageAssignedOn',
    andOr: 'or',
    changeAndOr: false,
  },
  {
    colName: 'Starts by User',
    colWidth: 200,
    flexGrow: 3,
    col: 'StartsByUser',
    fixed: true,
    sortable: true,
    type: 'startByUserId',
    field: 'StartsByUser',
    andOr: 'or',
    changeAndOr: false,
  },
  {
    colName: 'Package Status',
    colWidth: 200,
    flexGrow: 3,
    col: 'PackageStatus',
    fixed: true,
    sortable: true,
    type: 'packageStatus',
    field: 'PackageStatus',
    andOr: 'or',
    changeAndOr: false,
  },

  {
    colName: 'Package Name',
    colWidth: 200,
    flexGrow: 3,
    col: 'PackageName',
    fixed: true,
    sortable: true,
    type: 'packageId',
    field: 'PackageName',
    andOr: 'or',
    changeAndOr: false,
  },
  {
    colName: 'Department',
    colWidth: 200,
    flexGrow: 3,
    col: 'Department',
    fixed: true,
    sortable: true,
    type: 'department',
    field: 'Department',
    andOr: 'and',
    changeAndOr: false,
  },

  {
    colName: 'Job Title',
    colWidth: 200,
    flexGrow: 3,
    col: 'JobTitle',
    fixed: true,
    sortable: true,
    type: 'jobTitle',
    field: 'JobTitle',
    placeholder: 'Enter a job title',
    andOr: 'and',
    changeAndOr: false,
  },
  {
    colName: 'Job Code',
    colWidth: 200,
    flexGrow: 3,
    col: 'title',
    fixed: true,
    sortable: true,
    type: 'jobCode',
    field: 'code',
    placeholder: 'Enter a job code',
    andOr: 'and',
    changeAndOr: false,
  },
];
